"""Exploratory statistics. Everything here informs a modeling choice; results -> NOTES.md.

Questions (Tulsky/Silver framing):
  1. How repeatable is team quality season-over-season (1-lag and 2-lag)?  -> carryover, AR(1)
  2. Do process metrics (xG%) out-predict results (pts%, GF%) one season ahead? -> blend weight
  3. Is PDO (sh%+sv%) mostly luck?                                          -> regression logic
  4. Home-ice advantage size and drift                                      -> HFA parameter
  5. OT/SO frequency and skill-compression in OT                            -> game model
  6. Scoring environment and points spread by season                        -> calibration targets
"""
from pathlib import Path

import numpy as np
import pandas as pd

PROJ = Path(__file__).resolve().parents[1]
ts = pd.read_csv(PROJ / "data/processed/team_seasons.csv")
g = pd.read_csv(PROJ / "data/processed/games.csv", keep_default_na=False)
r = g[g.game_type == "R"].copy()

lines = ["# EDA findings (auto-generated by src/eda.py)", ""]


def w(s=""):
    print(s)
    lines.append(s)


# ---------- 1. League environment by season ----------
w("## League environment (regular season)")
w("season | gpg (incl SO) | %OT/SO | %SO | home_win% | mean pts/82 | sd pts/82")
env_rows = {}
for season, grp in r.groupby("season_end"):
    gpg = (grp.home_g + grp.away_g).mean()
    pot = (grp.went_ot | grp.went_so).mean()
    pso = grp.went_so.mean()
    hw = (grp.margin > 0).mean()
    t = ts[ts.season_end == season]
    mean82 = (t.pts_pct * 164).mean()
    sd82 = (t.pts_pct * 164).std(ddof=1)
    env_rows[season] = dict(pot=pot, hw=hw, sd82=sd82)
    w(f"{season} | {gpg:.2f} | {pot:.3f} | {pso:.3f} | {hw:.3f} | {mean82:.1f} | {sd82:.1f}")

# ---------- 2. Year-over-year reliability ----------
w("\n## Repeatability (franchise-matched pairs)")
tss = ts.sort_values(["team", "season_end"]).copy()
metrics = ["pts_pct", "gf_pct", "xg_pct_5v5", "xg_pct_all", "pdo", "sh_pct", "sv_pct"]
for lag in (1, 2):
    cur = tss.copy()
    nxt = tss.copy()
    nxt["season_end"] -= lag
    m = cur.merge(nxt, on=["team", "season_end"], suffixes=("_t", "_n"))
    w(f"\n### lag {lag}  (n={len(m)} pairs)")
    for met in metrics:
        a, b = m[f"{met}_t"], m[f"{met}_n"]
        ok = a.notna() & b.notna()
        rho = np.corrcoef(a[ok], b[ok])[0, 1]
        w(f"corr({met}_t, {met}_t+{lag}) = {rho:+.3f}")
    # cross-predictors of future points
    for met in ["pts_pct", "gf_pct", "xg_pct_5v5", "xg_pct_all", "pdo"]:
        a, b = m[f"{met}_t"], m["pts_pct_n"]
        ok = a.notna() & b.notna()
        rho = np.corrcoef(a[ok], b[ok])[0, 1]
        w(f"corr({met}_t, pts_pct_t+{lag}) = {rho:+.3f}")
    # regression slope & residual sd for pts_pct (shrinkage + innovation)
    ok = m["pts_pct_t"].notna() & m["pts_pct_n"].notna()
    x, y = m.loc[ok, "pts_pct_t"], m.loc[ok, "pts_pct_n"]
    slope = np.polyfit(x, y, 1)[0]
    resid = y - np.polyval(np.polyfit(x, y, 1), x)
    w(f"OLS pts_pct_t+{lag} ~ pts_pct_t: slope={slope:.3f}, resid_sd(pts/82)={resid.std(ddof=1)*164:.2f}")

# bivariate: does xG add to points? (standardized, lag-1, 2008+ pairs)
cur = tss.copy(); nxt = tss.copy(); nxt["season_end"] -= 1
m = cur.merge(nxt, on=["team", "season_end"], suffixes=("_t", "_n"))
m = m.dropna(subset=["pts_pct_t", "xg_pct_5v5_t", "pts_pct_n"])
X = np.column_stack([
    (m.pts_pct_t - m.pts_pct_t.mean()) / m.pts_pct_t.std(),
    (m.xg_pct_5v5_t - m.xg_pct_5v5_t.mean()) / m.xg_pct_5v5_t.std(),
    np.ones(len(m)),
])
y = (m.pts_pct_n - m.pts_pct_n.mean()) / m.pts_pct_n.std()
beta, *_ = np.linalg.lstsq(X, y, rcond=None)
r2 = 1 - ((y - X @ beta) ** 2).sum() / (y ** 2).sum()
w(f"\nstd betas for pts_pct_t+1: pts {beta[0]:+.3f}, xg5v5 {beta[1]:+.3f} (R2={r2:.3f}, n={len(m)})")
w(f"implied blend weight on results vs process ~ {beta[0]/(beta[0]+beta[1]):.2f} / {beta[1]/(beta[0]+beta[1]):.2f}")

# ---------- 3. OT skill compression ----------
w("\n## OT/SO structure")
ot = r[(r.went_ot | r.went_so)].copy()
w(f"share of R games past regulation, all years: {len(ot)/len(r):.3f}")
for era, lo, hi in (("pre-3v3 (2006-2015)", 2006, 2015), ("3v3 era (2016-2026)", 2016, 2026)):
    sub = r[(r.season_end >= lo) & (r.season_end <= hi)]
    o = sub[sub.went_ot | sub.went_so]
    w(f"{era}: OT share {len(o)/len(sub):.3f}, SO|past-reg {o.went_so.mean():.3f}, home wins OT games {(o.margin>0).mean():.3f}")
# does strength predict OT wins? proxy: season pts% diff vs OT result
ot = ot.merge(ts[["season_end", "team", "pts_pct"]], left_on=["season_end", "home"],
              right_on=["season_end", "team"]).rename(columns={"pts_pct": "h_pp"}).drop(columns="team")
ot = ot.merge(ts[["season_end", "team", "pts_pct"]], left_on=["season_end", "away"],
              right_on=["season_end", "team"]).rename(columns={"pts_pct": "a_pp"}).drop(columns="team")
ot["hwin"] = (ot.margin > 0).astype(int)
ot["dpp"] = ot.h_pp - ot.a_pp
# compare: P(better team wins | OT) vs P(better team wins | regulation)
reg = r[~(r.went_ot | r.went_so)].copy()
reg = reg.merge(ts[["season_end", "team", "pts_pct"]], left_on=["season_end", "home"],
                right_on=["season_end", "team"]).rename(columns={"pts_pct": "h_pp"}).drop(columns="team")
reg = reg.merge(ts[["season_end", "team", "pts_pct"]], left_on=["season_end", "away"],
                right_on=["season_end", "team"]).rename(columns={"pts_pct": "a_pp"}).drop(columns="team")
reg["dpp"] = reg.h_pp - reg.a_pp
for name, d in (("regulation-decided", reg), ("OT/SO-decided", ot)):
    better_home = d[d.h_pp > d.a_pp]
    better_away = d[d.a_pp > d.h_pp]
    p = (len(better_home[better_home.margin > 0]) + len(better_away[better_away.margin < 0])) / (len(better_home) + len(better_away))
    w(f"P(better season-team wins | {name}) = {p:.3f}")
# logistic-style slope: hwin ~ dpp (linear prob approx is fine for EDA)
sl = np.polyfit(ot.dpp, ot.hwin, 1)
sl_reg = np.polyfit(reg.dpp, (reg.margin > 0).astype(int), 1)
w(f"linear slope P(home win) vs pts%diff: regulation {sl_reg[0]:.2f}, OT/SO {sl[0]:.2f} "
  f"(compression ratio {sl[0]/sl_reg[0]:.2f})")

# ---------- 4. Recency of home advantage ----------
w("\n## Home ice")
for lo, hi in ((2006, 2013), (2014, 2019), (2022, 2026)):
    sub = r[(r.season_end >= lo) & (r.season_end <= hi)]
    w(f"{lo}-{hi}: home win% {( sub.margin>0).mean():.3f}")

# ---------- 5. Parity trend ----------
recent_sd = np.mean([env_rows[s]["sd82"] for s in range(2022, 2027)])
w(f"\nmean sd(pts/82) 2022-2026: {recent_sd:.1f}")

(PROJ / "NOTES.md").write_text("\n".join(lines) + "\n")
print("\nwritten to NOTES.md")
