"""v6 EDA (PLAN_V6 E-style) — writes output/eda_v6.md.

1. Team-season battery for the new metrics (shift concentration/continuity,
   coach change/tenure, schedule travel load) — full-sample descriptive.
2. Train-window (2014-2017 h1) incremental correlations vs the v5 walk-forward
   residuals, for the five F4 candidates.
3. Player-level EDGE repeatability (lag-1 within player, 2022+).
4. Absence-spell structure: age profile and player persistence of injury rate.
"""
import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent))
import engine as E
import ridge as R
from eda_v5 import fut_corr, lag_corr
from features_v6 import FEATURES_V5_ALL, FeatureBuilderV6

PROJ = Path(__file__).resolve().parents[1]
PROC = PROJ / "data" / "processed"
OUT = PROJ / "output"
CANDS = ["line_cont", "toi_hhi_f", "coach_new", "coach_tenure", "prospect_prod"]


def main():
    ts = pd.read_csv(PROC / "team_seasons.csv")
    v6 = pd.read_csv(PROC / "team_seasons_v6.csv")
    tv = pd.read_csv(PROC / "travel_games.csv", parse_dates=["date"])
    away = tv.groupby(["season_end", "away"]).agg(
        km_pg=("away_km", "mean"), tz_games=("away_dtz", lambda s: (s != 0).mean())
    ).reset_index().rename(columns={"away": "team"})
    df = ts.merge(v6, on=["season_end", "team"], how="left") \
        .merge(away, on=["season_end", "team"], how="left")

    lines = ["## v6 EDA (auto-generated by src/eda_v6.py)", "",
             "### 1. New-metric battery (full sample, descriptive)",
             "metric | n | lag1 r | lag2 r | r(pts_t) | r(pts_t+1)",
             "---|---|---|---|---|---"]
    for col in ("line_cont", "toi_hhi_f", "avg_shift_sec", "coach_new",
                "coach_tenure", "n_coaches", "km_pg", "tz_games"):
        sub = df.dropna(subset=[col])
        if len(sub) < 60:
            continue
        l1, _ = lag_corr(df, col, 1)
        l2, _ = lag_corr(df, col, 2)
        rf, _ = fut_corr(df, col)
        lines.append(f"{col} | {len(sub)} | {l1:+.3f} | {l2:+.3f} | "
                     f"{float(sub[col].corr(sub.pts_pct)):+.3f} | {rf:+.3f}")
    lines.append("")

    # ---------- 2. train-window residuals vs v5
    p2 = json.loads((OUT / "params_v2.json").read_text())
    p5 = json.loads((OUT / "params_v5.json").read_text())
    v1 = json.loads((OUT / "params.json").read_text())
    g, ts_full = E.load()
    _, end_r, _ = E.run_elo(g, K=v1["K"], H=v1["H"], phi_s=v1["phi_s"])
    fb = FeatureBuilderV6(end_r, ts_full, goalie_hp=p2["goalie_hp"],
                          skater_delta=p2["skater_delta"])
    feats, lam = p5["shipped"]["features_h1"], p5["shipped"]["lam_h1"]
    from features_v6 import FEATURES_V6_ALL
    X, y, meta = fb.feature_matrix(list(range(2012, 2018)), 1,
                                   feats=FEATURES_V6_ALL)
    idx = [FEATURES_V6_ALL.index(f) for f in feats]
    cidx = {c: FEATURES_V6_ALL.index(c) for c in CANDS}
    seasons = meta["T"].to_numpy()
    rows = []
    for T in range(2014, 2018):
        tr = (seasons < T) & ~np.isnan(y)
        te = seasons == T
        b = R.fit_ridge(X[tr][:, idx], y[tr], lam)
        pred = X[te][:, idx] @ b
        pred -= pred.mean()
        for k, (yy, pp) in enumerate(zip(y[te], pred)):
            row = {"resid_v5": yy - pp, "target": yy}
            for c, ci in cidx.items():
                row[c] = X[te][k, ci]
            rows.append(row)
    m2 = pd.DataFrame(rows)
    lines += ["### 2. Train-window incremental signal vs v5 residuals "
              "(2014-2017 h1, in-window)",
              "candidate | r(target dev) | r(v5 residual)", "---|---|---"]
    for c in CANDS:
        lines.append(f"{c} | {m2[c].corr(m2.target):+.3f} | "
                     f"{m2[c].corr(m2.resid_v5):+.3f}")
    lines.append("")

    # ---------- 3. EDGE player repeatability
    epp = PROC / "edge_players.csv"
    if epp.exists():
        ep = pd.read_csv(epp)
        lines += ["### 3. EDGE player-level repeatability (2022+)",
                  "metric | n pairs | lag1 r (within player)", "---|---|---"]
        for col in ("speed_max", "bursts_20", "bursts_22", "dist_total"):
            a = ep[["playerId", "season_end", col]].dropna()
            b = a.copy()
            b["season_end"] -= 1
            mm = a.merge(b, on=["playerId", "season_end"],
                         suffixes=("", "_fut")).dropna()
            if len(mm) > 50:
                lines.append(f"{col} | {len(mm)} | "
                             f"{mm[col].corr(mm[f'{col}_fut']):+.3f}")
        lines.append("")

    # ---------- 4. absence spells
    ab = pd.read_csv(PROC / "player_absences.csv")
    ab = ab[ab.window_games >= 20]
    ab["inj_rate"] = ab.injury_spell_games / ab.window_games
    a = ab[["playerId", "season_end", "inj_rate"]]
    b = a.copy()
    b["season_end"] -= 1
    mm = a.merge(b, on=["playerId", "season_end"], suffixes=("", "_fut"))
    lines += ["### 4. Absence spells (rosterSpots, 2012-2026)",
              f"- {len(ab)} qualifying player-seasons; injury-like share of missed "
              f"games {ab.injury_spell_games.sum() / max((ab.injury_spell_games + ab.scratch_games).sum(), 1):.3f}",
              f"- player injury-rate lag-1 persistence r = "
              f"{mm.inj_rate.corr(mm.inj_rate_fut):+.3f} (n={len(mm)}) — the "
              f"signal the S3 screen tests", ""]

    text = "\n".join(lines)
    (OUT / "eda_v6.md").write_text(text + "\n")
    print(text)


if __name__ == "__main__":
    main()
