"""v5 EDA (PLAN_V5 E) — auto-generates a NOTES-style markdown report.

Section 1  full-sample descriptive battery for every new team-season metric:
           coverage, lag-1/lag-2 franchise repeatability, contemporaneous and
           t+1 correlation with points%, era-split stability.
Section 2  TRAIN-WINDOW ONLY (predict-seasons 2014-2017, h1): correlation of each
           metric's vantage-V deviation with (a) the t+1 points deviation target and
           (b) the v4 walk-forward residual (shipped feats/lams) — incremental
           signal the incumbent misses. Selection-relevant analysis stays in-window.
Section 3  NHL EDGE (2022+): descriptive only (prereg'd report-only; too short to
           gate). Contemporaneous correlations + lag-1.
Section 4  PBP score-state: does 5v5 close-score SAT% carry signal beyond all-score?

Writes output/eda_v5.md and prints it. Descriptive full-sample stats follow the
NOTES v1 EDA precedent; nothing here tunes or selects (gates are backtest5.py).
"""
import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent))
import engine as E
import ridge as R
from features_v5 import FEATURES_V4, FeatureBuilderV5

PROJ = Path(__file__).resolve().parents[1]
PROC = PROJ / "data" / "processed"
OUT = PROJ / "output"

METRICS = ["fo_pct", "pen_net60", "pen_drawn60", "pen_taken60", "pp_pct", "pk_pct",
           "sat_pct", "hits60", "giveaways60", "takeaways60", "corsi_sa_pct",
           "flurry_xg5_pct", "hd_share_f", "hd_xg_pct", "rush_xg_pct",
           "rush_share_f", "srs", "sos", "fo_pct_pbp", "pen_net_g_pbp",
           "sat5_pct_pbp", "sat5_close_pct"]
REFERENCE = ["pts_pct", "xg_pct_5v5", "xg_pct_all"]   # incumbents for context


def lag_corr(df: pd.DataFrame, col: str, lag: int) -> tuple[float, int]:
    a = df[["season_end", "team", col]].dropna()
    b = a.copy()
    b["season_end"] -= lag
    m = a.merge(b, on=["season_end", "team"], suffixes=("", "_fut")).dropna()
    if len(m) < 30:
        return np.nan, len(m)
    return float(m[col].corr(m[f"{col}_fut"])), len(m)


def fut_corr(df: pd.DataFrame, col: str, target: str = "pts_pct",
             lo: int = 0, hi: int = 9999) -> tuple[float, int]:
    a = df[["season_end", "team", col]].dropna()
    b = df[["season_end", "team", target]].rename(columns={target: "_tgt_fut"})
    b["season_end"] -= 1
    m = a.merge(b, on=["season_end", "team"]).dropna()
    m = m[(m.season_end >= lo) & (m.season_end <= hi)]
    if len(m) < 30:
        return np.nan, len(m)
    return float(m[col].corr(m["_tgt_fut"])), len(m)


def main():
    ts = pd.read_csv(PROC / "team_seasons.csv")
    v5 = pd.read_csv(PROC / "team_seasons_v5.csv")
    df = ts.merge(v5, on=["season_end", "team"], how="left")
    # resolve PBP SAT attribution from the crosscheck record
    cc = json.loads((OUT / "v5_crosschecks.json").read_text()) \
        if (OUT / "v5_crosschecks.json").exists() else {}
    satcol = cc.get("sat_attribution", {}).get("chosen", "sat5_pct_own")
    if satcol in df.columns:
        df["sat5_pct_pbp"] = df[satcol]

    lines = ["## v5 EDA (auto-generated by src/eda_v5.py)", ""]

    # ---------- Section 1
    lines += ["### 1. New-metric battery (full sample, descriptive)",
              "metric | n | lag1 r | lag2 r | r(pts_t) | r(pts_t+1) | "
              "lag1 r 09-17 | lag1 r 18-26", "---|---|---|---|---|---|---|---"]
    for col in REFERENCE + [m for m in METRICS if m in df.columns]:
        keep = ["season_end", "team", col] + (["pts_pct"] if col != "pts_pct" else [])
        sub = df[keep].dropna(subset=[col])
        if not len(sub):
            continue
        l1, n1 = lag_corr(df, col, 1)
        l2, _ = lag_corr(df, col, 2)
        r_now = float(sub[col].corr(sub.pts_pct)) if len(sub) > 30 else np.nan
        r_fut, _ = fut_corr(df, col)
        e1 = lag_corr(df[df.season_end <= 2017], col, 1)[0]
        e2 = lag_corr(df[df.season_end >= 2017], col, 1)[0]
        tag = " (ref)" if col in REFERENCE else ""
        lines.append(f"{col}{tag} | {len(sub)} | {l1:+.3f} | {l2:+.3f} | "
                     f"{r_now:+.3f} | {r_fut:+.3f} | {e1:+.3f} | {e2:+.3f}")
    lines.append("")

    # ---------- Section 2: train-window incremental value
    lines += ["### 2. Train-window incremental signal (predict 2014-2017, h1; "
              "selection-relevant, in-window only)"]
    p2 = json.loads((OUT / "params_v2.json").read_text())
    p4 = json.loads((OUT / "params_v4.json").read_text())
    v1 = json.loads((OUT / "params.json").read_text())
    ship = p4["shipped"]
    g, ts_full = E.load()
    _, end_r, _ = E.run_elo(g, K=v1["K"], H=v1["H"], phi_s=v1["phi_s"])
    fb = FeatureBuilderV5(end_r, ts_full, goalie_hp=p2["goalie_hp"],
                          skater_delta=p2["skater_delta"])
    feats = ship["features_h1"]
    lam = ship["lam_h1"]
    X, y, meta = fb.feature_matrix(list(range(2012, 2018)), 1, feats=FEATURES_V4)
    idx = [FEATURES_V4.index(f) for f in feats]
    seasons = meta["T"].to_numpy()
    resid_rows = []
    for T in range(2014, 2018):
        tr = (seasons < T) & ~np.isnan(y)
        te = seasons == T
        b = R.fit_ridge(X[tr][:, idx], y[tr], lam)
        pred = X[te][:, idx] @ b
        pred -= pred.mean()
        for team, yy, pp in zip(meta.loc[te, "team"], y[te], pred):
            resid_rows.append({"season_end": T - 1, "team": team,
                               "target_dev": yy, "resid_v4": yy - pp})
    res = pd.DataFrame(resid_rows)   # keyed by vantage V = T-1
    dev = df.copy()
    for col in [m for m in METRICS if m in df.columns]:
        dev[col] = df[col] - df.groupby("season_end")[col].transform("mean")
    m2 = res.merge(dev, on=["season_end", "team"], how="left")
    lines += ["", "metric_dev(V) | n | r(target dev t+1) | r(v4 residual t+1)",
              "---|---|---|---"]
    for col in [m for m in METRICS if m in df.columns]:
        s = m2.dropna(subset=[col])
        if len(s) < 30:
            lines.append(f"{col} | {len(s)} | (n<30) | (n<30)")
            continue
        lines.append(f"{col} | {len(s)} | {s[col].corr(s.target_dev):+.3f} | "
                     f"{s[col].corr(s.resid_v4):+.3f}")
    lines.append("")

    # ---------- Section 3: EDGE
    ep = PROC / "edge_team.csv"
    if ep.exists():
        ed = pd.read_csv(ep).merge(ts[["season_end", "team", "pts_pct",
                                       "xg_pct_5v5"]], on=["season_end", "team"])
        lines += ["### 3. NHL EDGE (2022+, report-only by prereg — 4-5 seasons)",
                  "metric | n | r(pts_pct same yr) | r(xg5%) | lag1 r",
                  "---|---|---|---|---"]
        for col in [c for c in ed.columns if c not in
                    ("season_end", "team", "pts_pct", "xg_pct_5v5")]:
            s = ed.dropna(subset=[col])
            if len(s) < 20:
                continue
            l1, n1 = lag_corr(ed, col, 1)
            lines.append(f"{col} | {len(s)} | {s[col].corr(s.pts_pct):+.3f} | "
                         f"{s[col].corr(s.xg_pct_5v5):+.3f} | {l1:+.3f}")
        lines.append("")

    # ---------- Section 4: score-state
    if "sat5_close_pct" in df.columns:
        lines += ["### 4. PBP score-state (5v5 SAT% all-score vs close-score)"]
        s = df.dropna(subset=["sat5_close_pct", "sat5_pct_pbp"])
        r_all_fut, n1 = fut_corr(df, "sat5_pct_pbp")
        r_cl_fut, n2 = fut_corr(df, "sat5_close_pct")
        lines += [f"- corr(all, close) same season: "
                  f"{s.sat5_close_pct.corr(s.sat5_pct_pbp):+.3f} (n={len(s)})",
                  f"- r with pts_pct(t+1): all {r_all_fut:+.3f} (n={n1}) vs close "
                  f"{r_cl_fut:+.3f} (n={n2})", ""]

    text = "\n".join(lines)
    (OUT / "eda_v5.md").write_text(text + "\n")
    print(text)


if __name__ == "__main__":
    main()
